### ISSUE TITLE
Create a event card to be used on homepage calendar

### ISSUE THREAD

**Issue by yesyash** [Real-Dev-Squad/website-calendar#110]
### TODO
Need to create a event card for homepage calendar

### Reference
![image](https://user-images.githubusercontent.com/56453897/220966124-d714928c-0ddd-4181-a9bc-68a879416c88.png)

**Comment by Martijn0405** [comment]
@isVivek99 I would like to contribute to this issue.

**Comment by iRohitGaur** [comment]
> @isVivek99 I would like to contribute to this issue.

Hi @Martijn0405 . Are you on the RDS discord server?

**Comment by Martijn0405** [comment]
@iRohitGaur not yet. Haven't received an invite from Ankush on Twitter.

**Comment by iRohitGaur** [comment]
> @iRohitGaur not yet. Haven't received an invite from Ankush on Twitter.

No problem. Meanwhile you can start working on this issue.

**Comment by Martijn0405** [comment]
@iRohitGaur do you have any updates on the PR?

**Comment by iRohitGaur** [comment]
> @iRohitGaur do you have any updates on the PR?

We have already assigned this to you. I see that you have raised a PR for the same. @harshith-venkatesh has replied to you on the PR. Please check it out.
