### ISSUE TITLE
Add toast notifications library to the app

### ISSUE THREAD

**Issue by isVivek99** [Real-Dev-Squad/website-calendar#122]
eg: we can use `toastify` , if any other library is found we can discuss that before adding

**Comment by sonai99** [comment]
@isVivek99 I would like to work on this.

**Comment by isVivek99** [comment]
> @isVivek99 I would like to work on this.

done

**Comment by sonai99** [comment]
@isVivek99 you just want me to install toastify?
like do - yarn add react-toastify and raise pr? that's it?
