### ISSUE TITLE
Implementation of lint rules

### ISSUE THREAD

**Issue by Martijn0405** [Real-Dev-Squad/website-calendar#124]
I would like to make suggestions to introduce some new eslint rules to make parts of the code more consistent.

- Rule: [eslint[arrow-body-style]](https://eslint.org/docs/rules/arrow-body-style)
References: app/components/SocialAuth.tsx, app/components/icons/*, app/components/searchBar/index.tsx, app/models/oauth.server.ts, app/routes/onboardingUser/connect.tsx
```export const SocialAuth: React.FC<SocialAuthProps> = ({ google, microsoft }) => {
  return (
    <div className="flex flex-col w-full gap-4 my-8">
      <LinkButton icon={Google} title="Continue with Google" href={google} />

      <LinkButton icon={Microsoft} title="Continue with Microsoft" href={microsoft} />
    </div>
  );
};
```

- Rule: unnecessary assertion (sonarlint(typescript:S4325))
Reference: app/components/common/dropdown/index.test.tsx
Lines: 37
Code and fixed code:
```
const dropdownValue = screen.getByTestId('dropdown-value') as HTMLButtonElement;
const dropdownValue: HTMLButtonElement = screen.getByTestId('dropdown-value');
```

- Rule: duplicated import (sonarlint(css:S1128))
Reference: app/components/common/eventModal/styles.css
Lines: 3
```
@import '@radix-ui/colors/green.css';
```

- Rule: sonarlint(typescript:S6478)
Description: Do not define components during render. React will see a new component type on every render and destroy the entire subtree’s DOM nodes and state. Instead, move this component definition out of the parent component “UserOnboarding” and pass data as props.sonarlint(typescript:S6478)

- Rule: [eslint[no-undef]](https://eslint.org/docs/rules/no-undef)
Reference: app/components/Button.tsx
Description: 'React' is not defined

- Rule: [eslint[implicit-arrow-linebreak]](https://eslint.org/docs/rules/implicit-arrow-linebreak)
Reference: app/components/Calendar.tsx
Description: Expected no linebreak before this expression.

- Rule: [eslint[no-unused-vars]](https://eslint.org/docs/rules/no-unused-vars)
Reference: app/routes/onboardingUser/register.tsx
Description: 'data' is assigned a value but never used.

**Comment by Martijn0405** [comment]
@isVivek99 I would like to participate in fixing these and possibly future findings.

**Comment by isVivek99** [comment]
hi @Martijn0405 , thanks for creating this elaborate issue, I think we can implement some of them, before that , are you a part of the discord community of `Real dev squad` ?

**Comment by Martijn0405** [comment]
Hi @isVivek99, I am working on a project for our University about software evolution and we would like to contribute to this project by fixing a number of issues. We would like to join your discord. Could you please provide a way to join? I already signed up to the RealDevSquad website with GitHub too, if that helps.

**Comment by isVivek99** [comment]
I think you can contact @ankushdharkar on twitter if you would like to join `RDS`. you can contact him on twitter he will help you with this https://twitter.com/ankushdharkar
