### ISSUE TITLE
Create a constants file to store all the URLs

### ISSUE THREAD

**Issue by iRohitGaur** [Real-Dev-Squad/website-calendar#139]
Context:
https://github.com/Real-Dev-Squad/website-calendar/pull/119#issuecomment-1481370099

**Comment by saaagarsingh** [comment]
hey @iRohitGaur I would like to work on this.

**Comment by iRohitGaur** [comment]
> hey @iRohitGaur I would like to work on this.

Hi @saaagarsingh , are you in the discord server of RDS? If yes, can you please ping me there in #calendar-site-remix

**Comment by saaagarsingh** [comment]
Hey @iRohitGaur actually I'm not part of the discord server...can you suggest me a way to join?

**Comment by iRohitGaur** [comment]
> Hey @iRohitGaur actually I'm not part of the discord server...can you suggest me a way to join?

@saaagarsingh to get the server invite, please get in touch with Ankush on Twitter at https://twitter.com/ankushdharkar
