### ISSUE TITLE
Update the Readme.md file with Details of hosting the project in fly.io

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#14]
The project is temporarily deployed at ` https://rds-website-calendar.fly.dev/ `
Update the readme.MD file with information on fly.io and update host link with `https://rds-website-calendar.fly.dev/`

**Comment by oneonone97** [comment]
Hi Harshit! Can you assign this issue to me??
Thank You 😊😊

**Comment by harshith-venkatesh** [comment]
https://github.com/Real-Dev-Squad/website-calendar/pull/61

**Comment by harshith-venkatesh** [comment]
The above PR fixes the issue
