### ISSUE TITLE
Update the title of the website from New Remix App to RDS Website Calendar

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#15]

**Comment by Maianki** [comment]
Hi Harshith can you assign me this task?

**Comment by Maianki** [comment]
Hi, @harshith-venkatesh can you assign me this task?

**Comment by harshith-venkatesh** [comment]
@Maianki , I believe currently you are looking into this right?

**Comment by Maianki** [comment]
I have already raised PR for this issue. Link to the PR [PR for issue #15](https://github.com/Real-Dev-Squad/website-calendar/pull/27).
