### ISSUE TITLE
onboarding bugs

### ISSUE THREAD

**Issue by isVivek99** [Real-Dev-Squad/website-calendar#168]
- [ ]  user should not be able to continue to the next step if the username is already taken
- [ ]  prefetch the `onboarding/userCalendarDetails` route, when the user hovers over `save and next` on `STEP 1`
- [ ] user should not be able to visit `/onboarding` route, they should be redirected to `STEP 1` or `STEP 2`

**Comment by samyakshah3008** [comment]
I would like to work on this, @isVivek99 
Can you please assign this to me?
