### ISSUE TITLE
Create Contributing.md file with steps to follow for website calendar

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#17]
Ref : https://github.com/Real-Dev-Squad/website-members/pull/145/files

**Comment by harshith-venkatesh** [comment]
To create a good developer experience for the contribution, it would be better we create a documentation that helps with the steps for first contribution

**Comment by JAYATEJA04** [comment]
I want to take up this task and please assign it to me.
