### ISSUE TITLE
Create Pull Request Template for website calendar

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#18]
Create a template for website calendar to ensure the developers are following specific steps while raising the PR

Ref :https://github.com/Real-Dev-Squad/website-members/blob/develop/.github/pull_request_template.md

**Comment by aakankshadhurandhar** [comment]
@harshith-venkatesh  Can you assign me this issue ?

**Comment by aakankshadhurandhar** [comment]
@harshith-venkatesh  Do  I need to create PR template same as [ref](https://github.com/Real-Dev-Squad/website-members/blob/develop/.github/pull_request_template.md) ?
