### ISSUE TITLE
Create CODEOWNERS file to be included in .github folder

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#19]
Create Codeowners file in .github folder that should contain the rule

```
# Global Rule:
* @harshith-venkatesh @ankushdharkar
```

**Comment by pnchinmay** [comment]
Hey @harshith-venkatesh, can you assign me this issue ?

**Comment by dhanush027** [comment]
@harshith-venkatesh Can I take up this issue?

**Comment by harshith-venkatesh** [comment]
Sure , assigned @dhanush027

**Comment by dhanush027** [comment]
Thank you
