### ISSUE TITLE
while loging into calendar-site, instead of redirecting to current date user is getting redirected to the date on which they created a event

### ISSUE THREAD

**Issue by pronoyb07** [Real-Dev-Squad/website-calendar#197]
- while loging into calendar-site, instead of redirecting to the current date, the user is getting redirected to the date on which they created a event

**Comment by iRohitGaur** [comment]
Notes:
- need to look into caching.

Observed: if the date of an event is updated, it is still reflecting the old one on `/` for few minutes. To reproduce this, update an event's date by drag and drop and reload the page.
