### ISSUE TITLE
Fix high vulnerability issue of packages

### ISSUE THREAD

**Issue by dhanush027** [Real-Dev-Squad/website-calendar#28]
Reference:
![image](https://user-images.githubusercontent.com/79807326/172178271-7e637c20-16cb-422b-a2cb-c6735a8149f5.png)
Run : `npm audit fix`

**Comment by saigoud25** [comment]
Hey, I want to work on this. Can you detail that what I have to do?

**Comment by dhanush027** [comment]
Currently, 
If you notice while installing node modules, a warning pops up showing the vulnerabilities in the dependencies.
So you would need to run `npm audit fix`

**Comment by harshith-venkatesh** [comment]
@yesyash , Has this been addressed as well?

**Comment by harshith-venkatesh** [comment]
https://github.com/Real-Dev-Squad/website-calendar/pull/59
