### ISSUE TITLE
Create test setup for website-calendar

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#34]
[Jest](https://jestjs.io/)
[Jest-DOM](https://github.com/testing-library/jest-dom)
[React-Testing-Library](https://testing-library.com/docs)
[React-Testing-Library User-Event](https://github.com/testing-library/user-event)

We need to setup the test coverage as greater than 85% to ensure that we follow TDD from the beginning

**Comment by vinayak-trivedi** [comment]
Please assign this to me
