### ISSUE TITLE
Use yarn and volta

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-calendar#40]
Let's provide instructions on using volta and yarn, and how it helps with automatic node version switching

**Comment by harshith-venkatesh** [comment]
https://docs.volta.sh/guide/

Please use this PR for reference: https://github.com/Real-Dev-Squad/website-backend/pull/469/files

**Comment by Mir-SA** [comment]
Could i be assigned to this task?

**Comment by Mir-SA** [comment]
@harshith-venkatesh what should be the node version for this site?
same as backend or current version?

**Comment by Mir-SA** [comment]
Ok. I've actually raised a pr with  14x version but I'll change it.
Can you review it and let me know if it needs any other change?
