### ISSUE TITLE
README update - better dev experience

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#43]
# Yarn Command Reference

##### `yarn`

Installs all `dependencies` listed in the root `package.json`

Could you add this as well please.
This is currently missed.
And good to know that you have self reviewed and removed `run`

_Originally posted by @harshith-venkatesh in https://github.com/Real-Dev-Squad/website-calendar/issues/42#issuecomment-1213311996_

**Comment by harshith-venkatesh** [comment]
```

yarn
Installs all dependencies listed in the root package.json

```

Please add the above statements to the README.md file

**Comment by chiranjeevkapoor** [comment]
can i take this?

**Comment by chiranjeevkapoor** [comment]
[https://github.com/Real-Dev-Squad/website-calendar#using-a-template](url) , in here why is it ,npx create-remix@latest since we are using yarn??

**Comment by harshith-venkatesh** [comment]
Please remove using a template section as well as it is not relevant now
Thanks @chiranjeevkapoor for pointing it out

**Comment by chiranjeevkapoor** [comment]
@harshith-venkatesh will do when I raise the PR.

**Comment by vaibhav18matere** [comment]
can I take this task?

**Comment by harshith-venkatesh** [comment]
https://github.com/Real-Dev-Squad/website-calendar/pull/61
