### ISSUE TITLE
Create Navbar Component - Components Application

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#45]
<img width="101" alt="Screenshot 2022-10-20 at 8 52 35 AM" src="https://user-images.githubusercontent.com/44545218/196848906-a88d89c7-eeff-40f5-aecd-f4d990b7e9e1.png">

Build a navbar component that should expand on clicking on the navbar other than the menu icons.
Refer [Figma](https://www.figma.com/file/XKpdMCvntpMIaByuxTWBVN/RDS-Calendar-site?node-id=315%3A991) for more information on the icons

**Comment by ankurnarkhede** [comment]
@harshith-venkatesh , can you assign this to anyone? Its added for this week.

**Comment by isVivek99** [comment]
can i work on this?

**Comment by harshith-venkatesh** [comment]
Thanks @isVivek99 ,
Assigned

**Comment by harshith-venkatesh** [comment]
@ankurnarkhede updated
