### ISSUE TITLE
Create Pill Component - Components for Application

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#46]
<img width="236" alt="Screenshot 2022-10-20 at 8 56 38 AM" src="https://user-images.githubusercontent.com/44545218/196849395-e1cc4c67-dca0-465c-ba21-8881fee5e1c8.png">

Create an abstract Pill Components that should take in title, icon, color, action for on click of the pill
Refer [Figma](https://www.figma.com/file/XKpdMCvntpMIaByuxTWBVN/RDS-Calendar-site?node-id=315%3A991) for more information

**Comment by RitikJaiswal75** [comment]
I would love to work on this

**Comment by harshith-venkatesh** [comment]
<img width="480" alt="Screenshot 2022-11-17 at 8 09 37 AM" src="https://user-images.githubusercontent.com/44545218/202341354-31d7fc43-ff7f-451e-86b7-020d95f1b537.png">

@RitikJaiswal75 , Could we also look into handling close button in the pill.
X would be optional props
