### ISSUE TITLE
Prettier, ESLint, StyleLint, CommonLint Setup

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#6]
Please refer the link below for more information and comment in the issue for any doubts

- https://prettier.io/
- https://eslint.org/
- https://stylelint.io/user-guide/configure/
- https://commitlint.js.org/

**Comment by dhanush027** [comment]
Thank you

**Comment by dhanush027** [comment]
@harshith-venkatesh For ESlint setup which style guide is to be followed? Can I choose Airbnb style ?
![image](https://user-images.githubusercontent.com/79807326/166406231-93d1f37a-c683-45f2-bd85-dd3059774046.png)
