### ISSUE TITLE
Create a slider component with action button and close button 

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#66]
<img width="247" alt="Screenshot 2022-11-17 at 8 57 11 AM" src="https://user-images.githubusercontent.com/44545218/202347660-88761097-40dd-48ae-ac83-bcbf9ee32571.png">

https://www.figma.com/file/XKpdMCvntpMIaByuxTWBVN/RDS-Calendar-site?node-id=0%3A1&t=MRMptCDRBhBoMyUk-0

- Create a generic slider button which is expected to be present in the right side of the screen
- The slider is expected to contain a close button and an action button with content
- Ask for questions,doubts in #calendar-site-remix channel

**Comment by Maheima** [comment]
please assign it to me

**Comment by harshith-venkatesh** [comment]
@Maheima , how is the progress for slider component going on?

**Comment by harshith-venkatesh** [comment]
@Vedant-Manjrekar

**Comment by Vedant-Manjrekar** [comment]
> @Vedant-Manjrekar

I would like to work on this issue.

**Comment by Vedant-Manjrekar** [comment]
<img width="589" alt="Screenshot 2023-01-06 at 7 41 50 PM" src="https://user-images.githubusercontent.com/93585735/211028964-129a7d2d-0eaa-4f7f-ae20-b4f37048c9b7.png">

Doubts
1. How is the slider supposed to be triggered i.e. after clicking where should the slider come out.
2. Is is going to present throughout the site or is something specific to the events page.

**Comment by harshith-venkatesh** [comment]
The expectation is to create a generic slider that slides from the right side of the screen to left covering 220px width.
- On click of close icon or button should close the slider.

**Comment by harshith-venkatesh** [comment]
As per the discussion in the call, the doubts got clarified.

**Comment by Vedant-Manjrekar** [comment]
Got it @harshith-venkatesh, i will start working on it.

**Comment by harshith-venkatesh** [comment]
Thanks @Vedant-Manjrekar for the PR 
We will be closing the issue
