### ISSUE TITLE
Build pages for Onboarding process for RCal

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#69]
- Expected to build two pages, where connect button is expected to call a link so we could leave that function as it is as there will be follow up issue to integrate the onboarding process with backend.
- We need to provide the list of options for the timezone dropdown with selected current timezone of the user.
- We have available google and Microsoft icons available which could be utilized 
- We need to utilize the button component available
- 
<img width="332" alt="Screenshot 2022-11-22 at 9 40 23 PM" src="https://user-images.githubusercontent.com/44545218/203364120-e49af4cf-b61a-42bb-b948-f06418dbcbe0.png">
<img width="263" alt="Screenshot 2022-11-22 at 9 40 44 PM" src="https://user-images.githubusercontent.com/44545218/203364213-0302daef-eba6-498f-b757-68968821310b.png">

**Comment by isVivek99** [comment]
can i work on this task?

**Comment by ankurnarkhede** [comment]
@isVivek99 , you can start working on this issue.
