### ISSUE TITLE
Create Forgot Password Sign In Pages

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-calendar#72]
- User should be able to reset password on click of forgot password
- User would be asked for the email and a unique 4 digit code would be shared via email and adding the details would allow user to reset password
- Three screens are expected to be created as per the design
- Refer the design present in our discord channel 
<img width="913" alt="Screenshot 2022-12-02 at 7 23 52 AM" src="https://user-images.githubusercontent.com/44545218/205196928-18ff59c9-50ee-40a5-9b8a-1fe52a40a84b.png">
<img width="900" alt="Screenshot 2022-12-02 at 7 24 07 AM" src="https://user-images.githubusercontent.com/44545218/205196959-a4f4cf16-6f96-492a-9b97-7601e0c2d33d.png">

**Comment by bhtibrewal** [comment]
I would like to work on this task
